# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

lane :beta do
  build_app
end

lane :gym_build do
gym(
      clean: true,
      silent: true, 
      export_method: “ad-hoc”, 
      xcargs: "-allowProvisioningUpdates",
      #provisioning_profile_path: ‘/Users/alagrawa/Downloads/EBS__App_Hub__DEV.mobileprovision’,
      codesigning_identity: "iPhone Developer: Alok Agrawal (F3R982YKWY)" 

    )
end

end
